name: flutter_bloc_movie_app_example
description: Movie app with BLoC

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5
  rxdart: ^0.27.7
  dio: ^5.3.2
  go_router: ^10.0.0
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.0
  expandable: ^5.0.1
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/.env